.TH "src/modules/DebugManager Directory Reference" 3 "Tue Mar 7 2023" "Version 0.0.1" "WeighBridgeApplication" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/modules/DebugManager Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBDebugManager\&.cpp\fP"
.br
.ti -1c
.RI "file \fBDebugManager\&.h\fP"
.br
.in -1c
