.TH "Fts5PhraseIter" 3 "Tue Mar 7 2023" "Version 0.0.1" "WeighBridgeApplication" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Fts5PhraseIter
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <sqlite3\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "const unsigned char * \fBa\fP"
.br
.ti -1c
.RI "const unsigned char * \fBb\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB12369\fP of file \fBsqlite3\&.h\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "const unsigned char* Fts5PhraseIter::a"

.PP
Definition at line \fB12370\fP of file \fBsqlite3\&.h\fP\&.
.SS "const unsigned char* Fts5PhraseIter::b"

.PP
Definition at line \fB12371\fP of file \fBsqlite3\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for WeighBridgeApplication from the source code\&.
