.TH "Login" 3 "Tue Mar 7 2023" "Version 0.0.1" "WeighBridgeApplication" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Login
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <login\&.h>\fP
.PP
Inherits QDialog\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBLogin\fP (\fBMainWindow\fP *parent=0)"
.br
.ti -1c
.RI "\fB~Login\fP ()"
.br
.ti -1c
.RI "void \fBGetData\fP (QString &username, QString &password, QString &mode)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB15\fP of file \fBlogin\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Login::Login (\fBMainWindow\fP * parent = \fC0\fP)\fC [explicit]\fP"

.PP
Definition at line \fB9\fP of file \fBlogin\&.cpp\fP\&.
.SS "Login::~Login ()"

.PP
Definition at line \fB30\fP of file \fBlogin\&.cpp\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Login::GetData (QString & username, QString & password, QString & mode)"

.PP
Definition at line \fB47\fP of file \fBlogin\&.cpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for WeighBridgeApplication from the source code\&.
