.TH "src/modules/MainWindowManager/mainwindow.cpp" 3 "Tue Mar 7 2023" "Version 0.0.1" "WeighBridgeApplication" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/modules/MainWindowManager/mainwindow.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'mainwindow\&.h'\fP
.br
\fC#include <VideoFrameGrabber\&.h>\fP
.br
\fC#include 'ui_mainwindow\&.h'\fP
.br
\fC#include 'login\&.h'\fP
.br
\fC#include <uhfreader\&.h>\fP
.br
\fC#include <QNetworkReply>\fP
.br
\fC#include <QCloseEvent>\fP
.br
\fC#include <QCryptographicHash>\fP
.br
\fC#include <iomanip>\fP
.br
\fC#include 'weighmachinethread\&.h'\fP
.br
\fC#include <QMessageBox>\fP
.br
\fC#include <QMediaPlayer>\fP
.br
\fC#include <QMediaPlaylist>\fP
.br
\fC#include <QUrl>\fP
.br
\fC#include <CString>\fP
.br
\fC#include <iostream>\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for WeighBridgeApplication from the source code\&.
