.TH "src/modules/RfidManager/rfidmanager.h" 3 "Tue Mar 7 2023" "Version 0.0.1" "WeighBridgeApplication" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/modules/RfidManager/rfidmanager.h
.SH SYNOPSIS
.br
.PP
\fC#include 'qobject\&.h'\fP
.br
\fC#include 'qthread\&.h'\fP
.br
\fC#include 'rfidupdate\&.h'\fP
.br
\fC#include 'rfidnew\&.h'\fP
.br
\fC#include 'vehicleactions\&.h'\fP
.br
\fC#include <QString>\fP
.br
\fC#include <QVector>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBTag\fP"
.br
.ti -1c
.RI "class \fBRfidManager\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for WeighBridgeApplication from the source code\&.
