.TH "RfidNew" 3 "Tue Mar 7 2023" "Version 0.0.1" "WeighBridgeApplication" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RfidNew
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <rfidnew\&.h>\fP
.PP
Inherits QDialog\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBRfidNew\fP (\fBRfidManager\fP *parent=nullptr)"
.br
.ti -1c
.RI "\fB~RfidNew\fP ()"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fBVehicleActions\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB12\fP of file \fBrfidnew\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "RfidNew::RfidNew (\fBRfidManager\fP * parent = \fCnullptr\fP)\fC [explicit]\fP"

.PP
Definition at line \fB8\fP of file \fBrfidnew\&.cpp\fP\&.
.SS "RfidNew::~RfidNew ()"

.PP
Definition at line \fB50\fP of file \fBrfidnew\&.cpp\fP\&.
.SH "Friends And Related Function Documentation"
.PP 
.SS "friend class \fBVehicleActions\fP\fC [friend]\fP"

.PP
Definition at line \fB15\fP of file \fBrfidnew\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for WeighBridgeApplication from the source code\&.
