.TH "rfid" 3 "Fri Feb 24 2023" "Version 0.0.1" "WeighBridgeApplication" \" -*- nroff -*-
.ad l
.nh
.SH NAME
rfid
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <rfid\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBnet_connect\fP (QString HOST_IP, QString HOST_PORT, QString READER_IP, QString READER_PORT)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB4\fP of file \fBrfid\&.h\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "rfid::net_connect (QString HOST_IP, QString HOST_PORT, QString READER_IP, QString READER_PORT)"


.SH "Author"
.PP 
Generated automatically by Doxygen for WeighBridgeApplication from the source code\&.
