.TH "src/modules/RfidManager/rfidmanager.cpp" 3 "Tue Mar 7 2023" "Version 0.0.1" "WeighBridgeApplication" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/modules/RfidManager/rfidmanager.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'rfidmanager\&.h'\fP
.br
\fC#include 'uhfreader\&.h'\fP
.br
\fC#include 'mainwindow\&.h'\fP
.br
\fC#include <QDebug>\fP
.br
\fC#include <QDateTime>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "QString \fBgetStringFromUnsignedChar\fP (unsigned char *str)"
.br
.ti -1c
.RI "QString \fBgetStr\fP (unsigned char *str, int start, int end)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "QString getStr (unsigned char * str, int start, int end)"

.PP
Definition at line \fB113\fP of file \fBrfidmanager\&.cpp\fP\&.
.SS "QString getStringFromUnsignedChar (unsigned char * str)"

.PP
Definition at line \fB92\fP of file \fBrfidmanager\&.cpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for WeighBridgeApplication from the source code\&.
