.TH "sqlite3_rtree_geometry" 3 "Tue Mar 7 2023" "Version 0.0.1" "WeighBridgeApplication" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sqlite3_rtree_geometry
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <sqlite3\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "void * \fBpContext\fP"
.br
.ti -1c
.RI "int \fBnParam\fP"
.br
.ti -1c
.RI "\fBsqlite3_rtree_dbl\fP * \fBaParam\fP"
.br
.ti -1c
.RI "void * \fBpUser\fP"
.br
.ti -1c
.RI "void(* \fBxDelUser\fP )(void *)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB10531\fP of file \fBsqlite3\&.h\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBsqlite3_rtree_dbl\fP* sqlite3_rtree_geometry::aParam"

.PP
Definition at line \fB10534\fP of file \fBsqlite3\&.h\fP\&.
.SS "int sqlite3_rtree_geometry::nParam"

.PP
Definition at line \fB10533\fP of file \fBsqlite3\&.h\fP\&.
.SS "void* sqlite3_rtree_geometry::pContext"

.PP
Definition at line \fB10532\fP of file \fBsqlite3\&.h\fP\&.
.SS "void* sqlite3_rtree_geometry::pUser"

.PP
Definition at line \fB10535\fP of file \fBsqlite3\&.h\fP\&.
.SS "void(* sqlite3_rtree_geometry::xDelUser) (void *)"

.PP
Definition at line \fB10536\fP of file \fBsqlite3\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for WeighBridgeApplication from the source code\&.
