.TH "sqlite3_file" 3 "Tue Mar 7 2023" "Version 0.0.1" "WeighBridgeApplication" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sqlite3_file
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <sqlite3\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "const struct \fBsqlite3_io_methods\fP * \fBpMethods\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB724\fP of file \fBsqlite3\&.h\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "const struct \fBsqlite3_io_methods\fP* sqlite3_file::pMethods"

.PP
Definition at line \fB725\fP of file \fBsqlite3\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for WeighBridgeApplication from the source code\&.
