.TH "sqlite3_pcache_page" 3 "Tue Mar 7 2023" "Version 0.0.1" "WeighBridgeApplication" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sqlite3_pcache_page
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <sqlite3\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "void * \fBpBuf\fP"
.br
.ti -1c
.RI "void * \fBpExtra\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB8658\fP of file \fBsqlite3\&.h\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "void* sqlite3_pcache_page::pBuf"

.PP
Definition at line \fB8659\fP of file \fBsqlite3\&.h\fP\&.
.SS "void* sqlite3_pcache_page::pExtra"

.PP
Definition at line \fB8660\fP of file \fBsqlite3\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for WeighBridgeApplication from the source code\&.
