.TH "src/modules/CctvManager/videoframegrabber.cpp" 3 "Tue Mar 7 2023" "Version 0.0.1" "WeighBridgeApplication" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/modules/CctvManager/videoframegrabber.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'VideoFrameGrabber\&.h'\fP
.br
\fC#include <QtWidgets>\fP
.br
\fC#include <qabstractvideosurface\&.h>\fP
.br
\fC#include <qvideosurfaceformat\&.h>\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for WeighBridgeApplication from the source code\&.
