.TH "src/modules/CctvManager/videoframegrabber.h" 3 "Tue Mar 7 2023" "Version 0.0.1" "WeighBridgeApplication" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/modules/CctvManager/videoframegrabber.h
.SH SYNOPSIS
.br
.PP
\fC#include 'qabstractvideosurface\&.h'\fP
.br
\fC#include <QtWidgets>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBVideoFrameGrabber\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for WeighBridgeApplication from the source code\&.
