.TH "src/modules/WeighMachineManager/weighmachinethread.cpp" 3 "Tue Mar 7 2023" "Version 0.0.1" "WeighBridgeApplication" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/modules/WeighMachineManager/weighmachinethread.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'weighmachinethread\&.h'\fP
.br
\fC#include <QMessageBox>\fP
.br
\fC#include <QtSerialPort\\QSerialPort>\fP
.br
\fC#include <QRegularExpression>\fP
.br
\fC#include <QTextCodec>\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for WeighBridgeApplication from the source code\&.
