.TH "sources Directory Reference" 3 "Fri Feb 24 2023" "Version 0.0.1" "WeighBridgeApplication" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sources Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBDebugManager\&.cpp\fP"
.br
.ti -1c
.RI "file \fBlogin\&.cpp\fP"
.br
.ti -1c
.RI "file \fBmain\&.cpp\fP"
.br
.ti -1c
.RI "file \fBmainwindow\&.cpp\fP"
.br
.ti -1c
.RI "file \fBpsqlmanager\&.cpp\fP"
.br
.ti -1c
.RI "file \fBrfid\&.cpp\fP"
.br
.ti -1c
.RI "file \fBweighmachinethread\&.cpp\fP"
.br
.in -1c
