.TH "src/modules/RfidManager Directory Reference" 3 "Tue Mar 7 2023" "Version 0.0.1" "WeighBridgeApplication" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/modules/RfidManager Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBrfidmanager\&.cpp\fP"
.br
.ti -1c
.RI "file \fBrfidmanager\&.h\fP"
.br
.ti -1c
.RI "file \fBrfidnew\&.cpp\fP"
.br
.ti -1c
.RI "file \fBrfidnew\&.h\fP"
.br
.ti -1c
.RI "file \fBrfidreissue\&.cpp\fP"
.br
.ti -1c
.RI "file \fBrfidreissue\&.h\fP"
.br
.ti -1c
.RI "file \fBrfidupdate\&.cpp\fP"
.br
.ti -1c
.RI "file \fBrfidupdate\&.h\fP"
.br
.ti -1c
.RI "file \fBvehicleactions\&.cpp\fP"
.br
.ti -1c
.RI "file \fBvehicleactions\&.h\fP"
.br
.in -1c
