.TH "src/modules/DebugManager/DebugManager.h" 3 "Tue Mar 7 2023" "Version 0.0.1" "WeighBridgeApplication" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/modules/DebugManager/DebugManager.h
.SH SYNOPSIS
.br
.PP
\fC#include <QMap>\fP
.br
\fC#include <QDialog>\fP
.br
\fC#include <QMetaEnum>\fP
.br
\fC#include <QSqlDatabase>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBDebugManager\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBUi\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBDEBUGMANAGER_H\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum class \fBLogTypes\fP { \fBInfo\fP, \fBWarning\fP, \fBAlert\fP }"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define DEBUGMANAGER_H"

.PP
Definition at line \fB3\fP of file \fBDebugManager\&.h\fP\&.
.SH "Enumeration Type Documentation"
.PP 
.SS "enum class \fBLogTypes\fP\fC [strong]\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIInfo \fP\fP
.TP
\fB\fIWarning \fP\fP
.TP
\fB\fIAlert \fP\fP
.PP
Definition at line \fB10\fP of file \fBDebugManager\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for WeighBridgeApplication from the source code\&.
