.TH "src/modules/LoginManager/login.h" 3 "Tue Mar 7 2023" "Version 0.0.1" "WeighBridgeApplication" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/modules/LoginManager/login.h
.SH SYNOPSIS
.br
.PP
\fC#include 'qlineedit\&.h'\fP
.br
\fC#include <QDialog>\fP
.br
\fC#include <QSqlDatabase>\fP
.br
\fC#include <QDebug>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBLogin\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBUi\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBLOGIN_H\fP"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define LOGIN_H"

.PP
Definition at line \fB4\fP of file \fBlogin\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for WeighBridgeApplication from the source code\&.
