.TH "src/modules/LoginManager/login.cpp" 3 "Tue Mar 7 2023" "Version 0.0.1" "WeighBridgeApplication" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/modules/LoginManager/login.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'login\&.h'\fP
.br
\fC#include 'ui_login\&.h'\fP
.br
\fC#include <QDialog>\fP
.br
\fC#include <QMessageBox>\fP
.br
\fC#include 'mainwindow\&.h'\fP
.br
\fC#include <QCloseEvent>\fP
.br
\fC#include <QAction>\fP
.br
\fC#include <QToolButton>\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for WeighBridgeApplication from the source code\&.
