.TH "src/modules/MainWindowManager/mainwindow.h" 3 "Tue Mar 7 2023" "Version 0.0.1" "WeighBridgeApplication" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/modules/MainWindowManager/mainwindow.h
.SH SYNOPSIS
.br
.PP
\fC#include 'sodatamanager\&.h'\fP
.br
\fC#include 'src/modules/RfidManager/rfidmanager\&.h'\fP
.br
\fC#include <QMainWindow>\fP
.br
\fC#include <QDialog>\fP
.br
\fC#include <QSqlDatabase>\fP
.br
\fC#include <QNetworkAccessManager>\fP
.br
\fC#include <QDebug>\fP
.br
\fC#include 'psqlmanager\&.h'\fP
.br
\fC#include 'login\&.h'\fP
.br
\fC#include <QLibrary>\fP
.br
\fC#include 'weighmachinethread\&.h'\fP
.br
\fC#include 'DebugManager\&.h'\fP
.br
\fC#include 'sqlite3\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBMainWindow\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBUi\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBMAINWINDOW_H\fP"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define MAINWINDOW_H"

.PP
Definition at line \fB5\fP of file \fBmainwindow\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for WeighBridgeApplication from the source code\&.
