.TH "src/modules/PsqlManager/psqlmanager.h" 3 "Tue Mar 7 2023" "Version 0.0.1" "WeighBridgeApplication" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/modules/PsqlManager/psqlmanager.h
.SH SYNOPSIS
.br
.PP
\fC#include <QSqlDatabase>\fP
.br
\fC#include <QDebug>\fP
.br
\fC#include <QDate>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBPsqlManager\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for WeighBridgeApplication from the source code\&.
