.TH "RfidReissue" 3 "Tue Mar 7 2023" "Version 0.0.1" "WeighBridgeApplication" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RfidReissue
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <rfidreissue\&.h>\fP
.PP
Inherits QDialog\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBRfidReissue\fP (QWidget *parent=nullptr)"
.br
.ti -1c
.RI "\fB~RfidReissue\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB10\fP of file \fBrfidreissue\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "RfidReissue::RfidReissue (QWidget * parent = \fCnullptr\fP)\fC [explicit]\fP"

.PP
Definition at line \fB4\fP of file \fBrfidreissue\&.cpp\fP\&.
.SS "RfidReissue::~RfidReissue ()"

.PP
Definition at line \fB11\fP of file \fBrfidreissue\&.cpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for WeighBridgeApplication from the source code\&.
