.TH "docs/oldschool/Weightsmart/rfusbhid.h" 3 "Tue Mar 7 2023" "Version 0.0.1" "WeighBridgeApplication" \" -*- nroff -*-
.ad l
.nh
.SH NAME
docs/oldschool/Weightsmart/rfusbhid.h
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "int __stdcall \fBrdy_read\fP (unsigned char MemBank, unsigned char WordAdd, unsigned char WordCnt, unsigned char *PassWord, unsigned char *TagCount, unsigned char *DataLen, unsigned char *Data, unsigned char *ReadLen, unsigned char *AntID, unsigned char *ReadCount)"
.br
.ti -1c
.RI "int __stdcall \fBrdy_write\fP (unsigned char *PassWord, unsigned char MemBank, unsigned char WordAdd, unsigned char WordCnt, unsigned char *Data)"
.br
.ti -1c
.RI "int __stdcall \fBrdy_set_access_epc_match\fP (unsigned char Mode, unsigned char EpcLen, unsigned char *Epc)"
.br
.ti -1c
.RI "int __stdcall \fBget_firmware_version\fP (unsigned char *Version)"
.br
.ti -1c
.RI "int __stdcall \fBSetOutPower\fP (unsigned char Value)"
.br
.ti -1c
.RI "int __stdcall \fBGetOutPower\fP (unsigned char *Value)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int __stdcall get_firmware_version (unsigned char * Version)"

.SS "int __stdcall GetOutPower (unsigned char * Value)"

.SS "int __stdcall rdy_read (unsigned char MemBank, unsigned char WordAdd, unsigned char WordCnt, unsigned char * PassWord, unsigned char * TagCount, unsigned char * DataLen, unsigned char * Data, unsigned char * ReadLen, unsigned char * AntID, unsigned char * ReadCount)"

.SS "int __stdcall rdy_set_access_epc_match (unsigned char Mode, unsigned char EpcLen, unsigned char * Epc)"

.SS "int __stdcall rdy_write (unsigned char * PassWord, unsigned char MemBank, unsigned char WordAdd, unsigned char WordCnt, unsigned char * Data)"

.SS "int __stdcall SetOutPower (unsigned char Value)"

.SH "Author"
.PP 
Generated automatically by Doxygen for WeighBridgeApplication from the source code\&.
