.TH "sqlite3_index_info::sqlite3_index_constraint" 3 "Tue Mar 7 2023" "Version 0.0.1" "WeighBridgeApplication" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sqlite3_index_info::sqlite3_index_constraint
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <sqlite3\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBiColumn\fP"
.br
.ti -1c
.RI "unsigned char \fBop\fP"
.br
.ti -1c
.RI "unsigned char \fBusable\fP"
.br
.ti -1c
.RI "int \fBiTermOffset\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB7185\fP of file \fBsqlite3\&.h\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "int sqlite3_index_info::sqlite3_index_constraint::iColumn"

.PP
Definition at line \fB7186\fP of file \fBsqlite3\&.h\fP\&.
.SS "int sqlite3_index_info::sqlite3_index_constraint::iTermOffset"

.PP
Definition at line \fB7189\fP of file \fBsqlite3\&.h\fP\&.
.SS "unsigned char sqlite3_index_info::sqlite3_index_constraint::op"

.PP
Definition at line \fB7187\fP of file \fBsqlite3\&.h\fP\&.
.SS "unsigned char sqlite3_index_info::sqlite3_index_constraint::usable"

.PP
Definition at line \fB7188\fP of file \fBsqlite3\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for WeighBridgeApplication from the source code\&.
