.TH "Tag" 3 "Tue Mar 7 2023" "Version 0.0.1" "WeighBridgeApplication" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Tag
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <rfidmanager\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTag\fP (int \fBcounter\fP, int \fBfreqant\fP, int \fBrssi\fP, QString \fBpc\fP, int \fBepclen\fP, QString \fBepcdata\fP)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBcounter\fP"
.br
.ti -1c
.RI "int \fBfreqant\fP"
.br
.ti -1c
.RI "int \fBrssi\fP"
.br
.ti -1c
.RI "QString \fBpc\fP"
.br
.ti -1c
.RI "int \fBepclen\fP"
.br
.ti -1c
.RI "QString \fBepcdata\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB13\fP of file \fBrfidmanager\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Tag::Tag (int counter, int freqant, int rssi, QString pc, int epclen, QString epcdata)\fC [inline]\fP"

.PP
Definition at line \fB21\fP of file \fBrfidmanager\&.h\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "int Tag::counter"

.PP
Definition at line \fB14\fP of file \fBrfidmanager\&.h\fP\&.
.SS "QString Tag::epcdata"

.PP
Definition at line \fB19\fP of file \fBrfidmanager\&.h\fP\&.
.SS "int Tag::epclen"

.PP
Definition at line \fB18\fP of file \fBrfidmanager\&.h\fP\&.
.SS "int Tag::freqant"

.PP
Definition at line \fB15\fP of file \fBrfidmanager\&.h\fP\&.
.SS "QString Tag::pc"

.PP
Definition at line \fB17\fP of file \fBrfidmanager\&.h\fP\&.
.SS "int Tag::rssi"

.PP
Definition at line \fB16\fP of file \fBrfidmanager\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for WeighBridgeApplication from the source code\&.
