.TH "VehicleActions" 3 "Tue Mar 7 2023" "Version 0.0.1" "WeighBridgeApplication" \" -*- nroff -*-
.ad l
.nh
.SH NAME
VehicleActions
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <vehicleactions\&.h>\fP
.PP
Inherits QDialog\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBVehicleActions\fP (\fBRfidManager\fP *parent=nullptr)"
.br
.ti -1c
.RI "\fB~VehicleActions\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB12\fP of file \fBvehicleactions\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "VehicleActions::VehicleActions (\fBRfidManager\fP * parent = \fCnullptr\fP)\fC [explicit]\fP"

.PP
Definition at line \fB10\fP of file \fBvehicleactions\&.cpp\fP\&.
.SS "VehicleActions::~VehicleActions ()"

.PP
Definition at line \fB44\fP of file \fBvehicleactions\&.cpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for WeighBridgeApplication from the source code\&.
