name: print-directory-tree

on:
  push:
    branches:
      - main

jobs:
  print-directory-tree:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
            version: '5.15.2'
            host: 'windows'
            arch: 'win32_msvc2019'
            dir: 'C:\\Qt'
            qtModules: 'qtbase,qtdeclarative,qtquickcontrols2,qttools,qttranslations'
            vcVarsPath: '"C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\BuildTools\\VC\\Auxiliary\\Build\\vcvarsall.bat"'

      - name: List contents of C:\
        run: |
          ls C:\

      - name: Print working directory
        run: |
          echo "Present working directory:"
          pwd
      - name: Print directory subtree
        run: |
          echo "Directory subtree:"
          dir

      - name: Create downloads folder
        run: mkdir downloads

      - name: Download file
        run: |
          curl -L -o downloads/repogen.exe "https://firebasestorage.googleapis.com/v0/b/dwi-weightpro.appspot.com/o/repository%2Frepogen.exe?alt=media&token=d202fcd5-13da-4e96-8fe5-eca69c0e27f1"

      - name: Build online repository
        run: downloads/repogen.exe -p packages repository

      - name: Print directory subtree
        run: |
          echo "Directory subtree:"
          dir
          cd repository
          dir
          cd ..

      - name: Environment Setup
        run: |
          call "C:\Qt\5.15.2\msvc2019\bin\qtenv2.bat"
          call "C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Auxiliary\Build\vcvars32.bat"
          cd D:\a\Qt-WorkflowTest\Qt-WorkflowTest
          pwd
          dir
          
      - name: Build
        run: |
          cd src\A
          qmake 
          nmake
          nmake clean