name: Upload Final Output

on:
  push:
    branches:
      - repository

env:
  SOURCE_DIR:   ${{ github.workspace }}
  QT_VERSION:   5.15.2
  ARTIFACT:     deployment.zip

jobs:
  build-package-qt:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Zip build
        working-directory: ${{ runner.temp }}
        run:  |
              7z a deployment.zip ${{ env.SOURCE_DIR }}\repository\* -r
              
      - name: Save Build artifact
        uses: actions/upload-artifact@master
        with:
          name: ${{ env.ARTIFACT }}
          path: ${{ runner.temp }}\${{ env.ARTIFACT }}
