name: print-directory-tree

on:
  push:
    branches:
      - main

jobs:
  print-directory-tree:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Print working directory
        run: |
          echo "Present working directory:"
          pwd
      - name: Print directory subtree
        run: |
          echo "Directory subtree:"
          dir

      - name: Create downloads folder
        run: mkdir downloads

      - name: Download file
        run: |
          curl -L -o downloads/repogen.exe "https://firebasestorage.googleapis.com/v0/b/dwi-weightpro.appspot.com/o/repository%2Frepogen.exe?alt=media&token=d202fcd5-13da-4e96-8fe5-eca69c0e27f1"

      -name: Build online repository
        run: downloads/repogen.exe -p packages repository

      - name: Print directory subtree
        run: |
          echo "Directory subtree:"
          dir