name: print-directory-tree

on:
  push:
    branches:
      - main

jobs:
  print-directory-tree:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      
      - name: List contents of C:\
        run: |
          ls C:\
          ls C:\Julia

      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: '5.15.2'
          host: 'windows'
          target: 'desktop'
          arch: 'win32_msvc2019'
          dir: 'C:\'
          install-deps: 'true'
          modules: 'qtcharts qtwebengine'
          archives: 'qtbase qtsvg'
          cache: 'true'
          cache-key-prefix: 'install-qt-action'
          tools: 'tools_ifw tools_qtcreator,qt.tools.qtcreator'
          set-env: 'true'
          setup-python: 'false'
          tools-only: 'false'

      - name: Install Visual Studio Build Tools
        uses: microsoft/setup-msbuild@v1.0.2
        with:
          vs-version: 'latest'
          include-prerelease: true

      - name: Set up x86 environment
        shell: powershell
        run: |
          cmd /C ""C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Auxiliary\Build\vcvars32.bat"" 

      - name: List contents of C:\
        run: |
          ls C:\

      - name: Print working directory
        run: |
          echo "Present working directory:"
          pwd
      - name: Print directory subtree
        run: |
          echo "Directory subtree:"
          dir

      - name: Create downloads folder
        run: mkdir downloads

      - name: Download file
        run: |
          curl -L -o downloads/repogen.exe "https://firebasestorage.googleapis.com/v0/b/dwi-weightpro.appspot.com/o/repository%2Frepogen.exe?alt=media&token=d202fcd5-13da-4e96-8fe5-eca69c0e27f1"

      - name: Build online repository
        run: downloads/repogen.exe -p packages repository

      - name: Print directory subtree
        run: |
          echo "Directory subtree:"
          dir
          cd repository
          dir
          cd ..

      - name: Find my files
        run: |
          ls C:\Qt\5.15.2\msvc2019\bin\
          ls "C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Auxiliary\Build\"
         
      - name: Environment Setup
        run: |
          C:\Qt\5.15.2\msvc2019\bin\qtenv2.bat
          "C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Auxiliary\Build\vcvars32.bat"
          cd D:\a\Qt-WorkflowTest\Qt-WorkflowTest
          pwd
          dir
          
      - name: Build
        run: |
          cd src\A
          qmake 
          nmake
          nmake clean
          echo "hi1"