name: build-package-qt

on:
  push:
    branches:
      - main

env:
  SOURCE_DIR:   ${{ github.workspace }}
  QT_VERSION:   5.15.2
  ARTIFACT:     final-build.zip
  INSTALLER:    WeighPro-OnlineInstaller.zip

jobs:
  build-package-qt:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: repository

      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: '5.15.2'
          host: 'windows'
          target: 'desktop'
          arch: 'win32_msvc2019'
          dir: 'C:\'
          install-deps: 'true'
          modules: 'qtcharts qtwebengine'
          archives: 'qtbase qtsvg'
          cache: 'true'
          cache-key-prefix: 'install-qt-action'
          tools: 'tools_ifw tools_qtcreator,qt.tools.qtcreator'
          set-env: 'true'
          setup-python: 'false'
          tools-only: 'false'

      - name: Define cache key
        id: cache-key
        run: echo "::set-output name=key::$(echo 'http://download.qt.io/official_releases/jom/jom.zip' | md5sum | cut -d' ' -f1)"
        
      - name: Download and unzip JOM
        if: steps.cache-jom.outputs.cache-hit != 'true'
        uses: suisei-cn/actions-download-file@v1
        with:
          url: http://download.qt.io/official_releases/jom/jom.zip
          target: ${{ runner.temp }}
      - name: Unzip JOM
        if: steps.cache-jom.outputs.cache-hit != 'true'
        working-directory: ${{ runner.temp }}
        run: 7z x jom.zip -ojom
      
      - name: Cache JOM
        uses: actions/cache@v2
        id: cache-jom
        with:
          path: ${{ runner.temp }}/jom
          key: ${{ steps.cache-key.outputs.key }}  

      - name: Set up Visual Studio shell
        uses: egor-tensin/vs-shell@v2
        with:
          arch: x86

      - name: Create build directory
        run:  mkdir ${{ runner.temp }}\build

      - name: Build
        working-directory: ${{ runner.temp }}\build
        run:  |
              ls .
              qmake -r ${{ env.SOURCE_DIR }}\src\A\A.pro
              ${{ runner.temp }}\jom\jom -j2
              ls .
              cd release
              ${{ env.SOURCE_DIR }}\utils/windeployqt.exe A.exe --pdb --release --compiler-runtime
              ls .
              xcopy /s ${{ runner.temp }}\build\release\* ${{ env.SOURCE_DIR }}\packages\A\data\
      
      - name: Build online repository
        run: utils/repogen.exe -p packages repository

      - name: Commit changes of repository
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add ${{ env.SOURCE_DIR }}\repository\
          git commit -m "Updating Repository"

      - name: Push changes to repository branchs
        run: |
          git subtree push --prefix ${{ env.SOURCE_DIR }}\repository\ origin repository

      - name: Build Online Installer
        run: |
          utils/binarycreator.exe --online-only -c config/config.xml -p packages installer.exe
          xcopy /s ${{ runner.temp }}\installer.exe ${{ env.SOURCE_DIR }}\installer.exe

      - name: Zip build
        working-directory: ${{ runner.temp }}
        run:  |
              7z a WeighPro-OnlineInstaller.zip ${{ env.SOURCE_DIR }}\installer.exe -r

      - name: Save Online Installer
        uses: actions/upload-artifact@master
        with:
          name: ${{ env.INSTALLER }}
          path: ${{ runner.temp }}\${{ env.INSTALLER }}
